require: rubocop-rspec

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/**/*.rb'

Style:
  Documentation:
    Enabled: false

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/data_schema.rb'
    - 'db/data/*'
