FORMAT: 1A
HOST: https://bandejao.gjhhenrique.com


# Bandejao

Bandejao is a simple API to view the weekly meals of a registered restaurant.

## Weekly meals [/weekly/{university_name}]
Returns the weekly meals of the university

+ Parameters
    + university_name (string) - Name of the university. 
    It may be in lowercase or uppercase format
  

### List the weekly meals of this university [GET]

+ Response 200 (application/json)
    
        [
            {
                "date": "2016-04-10",
                "period": "LUNCH",
                "dishes": ["Vegetable Pie", "Carrot", "Roast Pork"]
            },
            {
                "date": "2016-04-11",
                "period": "DINNER",
                "dishes": ["Rice Pudding", "Jacked Potato", "Minced Beef"]
            }
        ]
        

## Weekly meals of university [/weekly/university/{university_name}]
Besides returning the weekly meals, it will also return the university information.

If the university has one or more campus, it will return the information of only its campuses.

+ Parameters
    + university_name (string) - Name of the university
    It may be in lowercase or uppercase format
  

### List the university information and the weekly meals of the university or its campuses [GET]

+ Response 200 (application/json)
    
        [
            {
                "name": "PU",
                "long_name": "Programming University",
                "website": "http://proplan.ufac.br/cardapio-ru",
                "meals":[
                    {
                        "date":"2016-07-18",
                        "period":"BREAKFAST",
                        "dishes": ["Rice Pudding", "Jacked Potato", "Minced Beef"]
                    }
                ]
            }
        ]