# frozen_string_literal: true

# Load DSL and set up stages
require 'capistrano/setup'

# Include default deployment tasks
require 'capistrano/deploy'

require 'capistrano/bundler'
require 'capistrano/rails/migrations'

require 'capistrano/puma'
require 'capistrano/puma/workers'
require 'capistrano/puma/jungle'
# TODO: Fix monit configuration
# require 'capistrano/puma/monit'
require 'capistrano/puma/nginx'

require 'sshkit/sudo'
require 'whenever/capistrano'

Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
