# frozen_string_literal: true

source 'https://rubygems.org'

gem 'capistrano'
gem 'capistrano-bundler', '~> 1.1.2'
gem 'capistrano-rails', '~> 1.1'
gem 'capistrano3-puma'
gem 'sshkit-sudo'
gem 'whenever'
