require: rubocop-rspec

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/data_schema.rb'
    - 'db/data/*'
