# frozen_string_literal: true

# require 'sinatra/activerecord/rake'
require 'rom/sql/rake_task'
require './bootstrap'

namespace :parsers do
  task :parse_universities do
    ParserJob.parse_all
  end

  task :parse_university, [:name] do |_, args|
    university = University.by_name args[:name]
    raise "There is no university with the name #{args[:name]}" if university.nil?

    ParserJob.parse_university university
  end
end

namespace :db do
  task :setup do
    Dotenv.load
    ROM::SQL::RakeSupport.env = ROM::Configuration.new(:sql, ENV['DATABASE_URL'])
  end
end
