# frozen_string_literal: true

require 'sinatra/activerecord/rake'
require './bootstrap'

namespace :parsers do
  task :parse_universities do
    ParserJob.parse_all
  end

  task :parse_university, [:name] do |_, args|
    university = University.by_name args[:name]
    raise "There is no university with the name #{args[:name]}" if university.nil?

    ParserJob.parse_university university
  end
end

namespace :gcm do
  task :send_message, [:name] do |_, args|
    university = University.by_name args[:name]
    ParserJob.send_gcm_request university.main_name
  end

  task :test_key do
    puts ENV['GCM_KEY']
  end
end

namespace :db do
  Sequel.extension :migration
  Dotenv.load
  DB = Sequel.connect(ENV['DATABASE_URL'])

  task :new_migrate do
    Sequel::Migrator.run(DB, 'migrations')
    Rake::Task['db:version'].execute
  end

  desc 'Perform migration reset (full rollback and migration)'
  task :new_reset do
    Sequel::Migrator.run(DB, 'migrations', target: 0)
    Sequel::Migrator.run(DB, 'migrations')
    Rake::Task['db:version'].execute
  end
end
