UEL:
  long_name: Universidade Estadual de Londrina
  website: http://www.uel.br/ru/pages/cardapio.php

UFAC:
  long_name: Universidade Federal do Acre
  website: http://proplan.ufac.br/cardapio-ru

Cambridge:
  long_name: University of Cambridge
  website: http://www.unicen.cam.ac.uk/food-and-drink/main-dining-hall
